# Host-side structural check; this is not an emulator or hardware launch test.
if(NOT DEFINED PBP_FILE OR NOT EXISTS "${PBP_FILE}")
    message(FATAL_ERROR "EBOOT.PBP was not produced: ${PBP_FILE}")
endif()
file(SIZE "${PBP_FILE}" pbp_size)
if(pbp_size LESS 40 OR pbp_size GREATER 67108864)
    message(FATAL_ERROR "Invalid PBP size: ${pbp_size}")
endif()
file(READ "${PBP_FILE}" header LIMIT 40 HEX)
string(SUBSTRING "${header}" 0 16 signature)
if(NOT signature STREQUAL "0050425000000100")
    message(FATAL_ERROR "Invalid PBP magic/version")
endif()
function(read_u32 hex offset out)
    math(EXPR byte_offset "${offset} * 2")
    set(value 0)
    foreach(byte RANGE 0 3)
        math(EXPR position "${byte_offset} + ${byte} * 2")
        string(SUBSTRING "${hex}" ${position} 2 pair)
        math(EXPR value "${value} + (0x${pair} << (${byte} * 8))")
    endforeach()
    set(${out} ${value} PARENT_SCOPE)
endfunction()
set(previous 40)
foreach(index RANGE 0 7)
    math(EXPR offset "8 + ${index} * 4")
    read_u32("${header}" ${offset} section_${index})
    if(section_${index} LESS previous OR section_${index} GREATER pbp_size)
        message(FATAL_ERROR "PBP section offsets are invalid")
    endif()
    set(previous ${section_${index}})
endforeach()
if(NOT section_0 EQUAL 40)
    message(FATAL_ERROR "PBP PARAM.SFO does not start after the header")
endif()
math(EXPR sfo_size "${section_1} - ${section_0}")
math(EXPR elf_size "${section_7} - ${section_6}")
if(sfo_size LESS 20 OR elf_size LESS 52)
    message(FATAL_ERROR "PBP is missing PARAM.SFO or a PSP executable")
endif()
file(READ "${PBP_FILE}" sfo OFFSET ${section_0} LIMIT 4 HEX)
if(NOT sfo STREQUAL "00505346")
    message(FATAL_ERROR "PBP PARAM.SFO signature is invalid")
endif()
file(READ "${PBP_FILE}" elf OFFSET ${section_6} LIMIT 20 HEX)
string(SUBSTRING "${elf}" 0 12 elf_format)
string(SUBSTRING "${elf}" 36 4 elf_machine)
if(NOT elf_format STREQUAL "7f454c460101" OR NOT elf_machine STREQUAL "0800")
    message(FATAL_ERROR "PBP must contain a little-endian ELF32 MIPS executable")
endif()
message(STATUS "Verified PSP package structure: ${PBP_FILE} (${pbp_size} bytes)")
