name: Combined CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml

  build-windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml

  build-psp:
    name: Build PSP
    uses: ./.github/workflows/build-psp.yml
