name: Combined CI

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml
    concurrency:
      group: btd4-repopped-linux-${{ github.ref }}
      cancel-in-progress: true

  build-windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml
    concurrency:
      group: btd4-repopped-windows-${{ github.ref }}
      cancel-in-progress: true
